#
# Module manifest for module 'RipClip'
#
# Generated by: Henrik Burchardt
#
# Generated on: 11/02/2026
#

@{

# Script module associated with this manifest.
RootModule = 'RipClip.psm1'

# Version number of this module.
ModuleVersion = '0.6.1'

# Supported PowerShell editions
CompatiblePSEditions = @('Core')

# Unique identifier
GUID = 'fd942298-7f9c-4cc6-9f3d-8c7f3b09801b'

# Author
Author = 'Henrik Burchardt'

# Company
CompanyName = 'Reservehjernen'

# Copyright
Copyright = '(c) Henrik Burchardt. All rights reserved.'

# Description
Description = 'Modular PowerShell-based YouTube audio downloader built on yt-dlp with playlist control and clipboard integration.'

# Minimum PowerShell version
PowerShellVersion = '7.0'

# -------------------------------------------------
# Export Configuration (THIS is what matters)
# -------------------------------------------------

FunctionsToExport = @(
    'Invoke-RipClip',
    'Get-RipClipEffectiveConfig'
)

CmdletsToExport   = @()
VariablesToExport = @()

AliasesToExport   = @(
    'rip'
)

# -------------------------------------------------
# PrivateData (Gallery metadata)
# -------------------------------------------------

PrivateData = @{

    PSData = @{

        Tags = @('powershell','yt-dlp','youtube','cli','open-source')

        LicenseUri = 'https://github.com/it-supporter/RipClip/blob/main/LICENSE'

        ProjectUri = 'https://github.com/it-supporter/RipClip'

        ReleaseNotes = 'Structured architecture, JSON config layering, diagnostics support.'

    }

}


}

